### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by NNoGalaxy** [davidbombal/red-python-scripts#28]
Traceback (most recent call last):
  File "e:/uwu/wifi.py", line 4, in <module>
    command_output = subprocess.run(["netsh", "wlan", "show", "profiles"], capture_output = True).stdout.decode()
  File "C:\Users\33138052\AppData\Local\Programs\Python\Python38\lib\site-packages\run\__init__.py", line 145, in __new__
    process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
  File "C:\Users\33138052\AppData\Local\Programs\Python\Python38\lib\site-packages\run\__init__.py", line 121, in create_process
    shlex.split(command),
  File "C:\Users\33138052\AppData\Local\Programs\Python\Python38\lib\shlex.py", line 310, in split
    return list(lex)
  File "C:\Users\33138052\AppData\Local\Programs\Python\Python38\lib\shlex.py", line 300, in __next__
    token = self.get_token()
  File "C:\Users\33138052\AppData\Local\Programs\Python\Python38\lib\shlex.py", line 109, in get_token
    raw = self.read_token()
  File "C:\Users\33138052\AppData\Local\Programs\Python\Python38\lib\shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'list' object has no attribute 'read'

Any fixes?

**Comment by bener07** [comment]
Well normally List methods (if i'm not wrong) don't have the read Attribute so there's the error if you use a debugger or something similar you will probably get more information. Then tell us.
